### ISSUE TITLE
TransactionAttributeType.REQUIRED is not working

### ISSUE THREAD

**Issue by gokhanoner** [hazelcast/hazelcast-ra#10]
Please see below. This seems to be not working.

Please see https://hazelcast.zendesk.com/agent/tickets/3744

```
@Singleton
@Startup
@Lock(LockType.READ)
public class QueueService {

    @Resource(name = "HazelcastCF")
    protected HazelcastConnectionFactory connectionFactory;

    @TransactionAttribute(TransactionAttributeType.REQUIRED)
    public void queueMessage(EQueueName queueName, Object message {
        HazelcastConnection c = null;
        try {
            c = connectionFactory.getConnection();
            TransactionalQueue<HzMessage> queue = c.getTransactionalQueue(queueState.getQueueIdentifier());

            boolean accepted = false;
            while (!accepted) {
                accepted = offerMessage(message, queue, queueName, sciId);
            }
        } catch (Exception e) {
            logger.log(Level.SEVERE, "Failed to Queue message", e);
        } finally {
            closeConnection(c);
        }
    }
    
}
```

**Comment by emre-aydin** [comment]
Which version of Glassfish did you try this with? 3?

**Comment by gokhanoner** [comment]
@emre-aydin Payara 4.1.173

**Comment by emre-aydin** [comment]
@gokhanoner this seems to be working for me, what am I missing? What should I look for? What's the error you're getting if any?

**Comment by gokhanoner** [comment]
@emre-aydin, customer gets no transaction exception. Can you also test calling this method while in another transaction?

**Comment by emre-aydin** [comment]
@emre thanks for the correction :) @gokhanoner I'll have a look.

**Comment by gokhanoner** [comment]
@emre-aydin Customer said that it occurs some cases, most probably mixed with other transactional boundaries. Maybe we should do some nested transaction tests to confirm if it's working.

**Comment by emre-aydin** [comment]
@gokhanoner as far as I can see from the discussion on ticket, nested transaction or not, this problem occurs. I wasn't able to reproduce the error.

**Comment by yozank** [comment]
https://github.com/hazelcast/hazelcast-ra/pull/11
