### ISSUE TITLE
Update JCA Resource Adapter for compatibility with Hazelcast 3.12

### ISSUE THREAD

**Issue by jcaprice** [hazelcast/hazelcast-ra#13]
The latest version of the Hazelcast JCA Resource Adapter is incompatible with Hazelcast 3.12, and was last built with Hazelcast 3.8.

The Resource Adapter fails to start with the below error, caused by changes to configuration introduced in 3.12. This one is caused by the renaming of AbstractConfigBuilder to AbstractXMLConfigBuilder from [this commit](https://github.com/hazelcast/hazelcast/commit/0cdb7bd1924edc4a1e384e203ca6282588359456). 

> Caused by: java.lang.ClassNotFoundException: com.hazelcast.config.AbstractConfigBuilder

**Comment by mesutcelik** [comment]
Hi @jcaprice ,

I did not see the problem you mention above but we were definitely missing new data structures. I added them via https://github.com/hazelcast/hazelcast-ra/pull/14

**Comment by alparslanavci** [comment]
@jcaprice is there any possibility to share the full exception stacktrace?

**Comment by mesutcelik** [comment]
closed via https://github.com/hazelcast/hazelcast-ra/pull/15
