### ISSUE TITLE
RA shouldn't cast to implementation when using container to get a connection

### ISSUE THREAD

**Issue by rmannibucau** [hazelcast/hazelcast-ra#3]
https://github.com/hazelcast/hazelcast-ra/blob/070e0c4a1ba2795f086bafcc58a37f188ec995dd/hazelcast-jca/src/main/java/com/hazelcast/jca/ConnectionFactoryImpl.java#L91 casts to HazelcastConnectionImpl without any reason at that location which prevents container to proxy the connection which can be needed for different needs. JCA being for now based on JDK proxying (Message Listener API is there only for that) it should get fixed IMHO (+ it doesnt hurt).

If you really need the impl it is trivial to add an unwrap() method to the listener API.

**Comment by mesutcelik** [comment]
Hi @rmannibucau ,

Isn't it fixed already or you are talking something else?

https://github.com/hazelcast/hazelcast-ra/blob/master/hazelcast-jca/src/main/java/com/hazelcast/jca/ConnectionFactoryImpl.java#L95

**Comment by rmannibucau** [comment]
oops, right (checked an earlier release). Is it released? (there is no tag on the project)

**Comment by mesutcelik** [comment]
3.6.x version of hazelcast-ra is still on hazelcast main repo and fix already backported to there.
https://github.com/hazelcast/hazelcast/pull/8019

Next stable release of hazelcast which will include hazelcast-ra is 3.6.3 and scheduled somewhere mid-May...

**Comment by rmannibucau** [comment]
Thanks a lot!
