### ISSUE TITLE
readme.md has a MarkDown Syntax error

### ISSUE THREAD

**Issue by mstier** [hazelcast/hazelcast-ra#9]
There is whitespace in front of the xml-tag In section "Configuring a JBoss AS 7 or EAP 6 Web Application". This prevents the module.xml to be rendered.

**Comment by mesutcelik** [comment]
Thanks for the heads up! @mstier !

fixed by https://github.com/hazelcast/hazelcast-ra/commit/7eb1dcdbb189d0de7730e773ed1c7213988bed8a
